/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.OrderDetailDLL;
import DLL.ProductDLL;
import DLL.UserDLL;
import Entity.OrderDetail;
import Entity.Product;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sang Luu Phuoc
 */
public class GuiOrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form GuiOrderDetail
     */
    // tạo Arraylist để chứa thông của thực thể
    ArrayList<OrderDetail> listorderdetail = new ArrayList<>();
    OrderDetailDLL ordedll = new OrderDetailDLL();

    ArrayList<User> listuser = new ArrayList<>();
    UserDLL userdll = new UserDLL();

    ArrayList<Product> listproduct = new ArrayList<>();
    ProductDLL prodll = new ProductDLL();

    public GuiOrderDetail() {
        initComponents();
        Bliding();
        Blidinguser();
        BlidingProduct();
        BlidingPayment();
        // lấy số hàng từ số lương khi chạy phương thức Bliding
        int row = tbshow.getRowCount();
        // vòng sét ID lớn nhất và in sẵn ID cho sản phẩm tiếp theo
        for (int i = 1; i < row; i++) {
            int max = Integer.parseInt(String.valueOf((tbshow.getValueAt(0, 0))));
            if (max < Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)))) {
                max = Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)));
            }
            max = max + 1;
            // in ra txt 
            txtMaDetailHD.setText(String.valueOf(max));
        }
    }

    // phương thực bảng động và add các giá trị vào bảng
    public void Bliding() {
        listorderdetail = ordedll.getAll();
        // số cột được add
        Vector colums = new Vector();
        colums.add("Mã chi tiết hóa đơn");
        colums.add("Ngày Lập");
        colums.add("Tên khách hàng");
        colums.add("Sản phẩm");
        colums.add("Số lượng");
        colums.add("Đơn giá");
        colums.add("Phương thức thức thanh toán");
        colums.add("Mã đơn");
        // số hàng đưuọc add
        Vector data = new Vector();
        // vọng lặp in gia trị
        for (OrderDetail orde : listorderdetail) {
            Vector row = new Vector();
            row.add(orde.getOrderDetailId());
            row.add(orde.getDate());
            listuser = userdll.getbyID(orde.getUserID());
            if (listuser.size() > 0) {
                row.add(listuser.get(0).getFullname());
            } else {
                row.add("Chua nhap");
            }
            listproduct = prodll.getbyIDfromOrder(orde.getProductID());
            if (listproduct.size() > 0) {
                row.add(listproduct.get(0).getname());
            } else {
                row.add("Chua nhap");
            }
            row.add(orde.getQuantity());
            row.add(orde.getPrice());
            row.add(orde.getPayment_method());
            row.add(orde.getOrderID());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, colums);
        // đưa vào bảng
        tbshow.setModel(dtm);
    }

    // phương thức lấy hết thông tin và add item để chọn
    public void Blidinguser() {
        listuser = userdll.getAll();
        for (User us : listuser) {
            cbTenKH.addItem(us.getFullname());
        }
    }

    // phương thức lấy hết thông tin và add item để chọn
    public void BlidingProduct() {
        listproduct = prodll.getAll();
        for (Product pr : listproduct) {
            cbSanpham.addItem(pr.getname());
        }
    }

    // phương thức lấy hết thông tin và add item để chọn
    public void BlidingPayment() {
        listorderdetail = ordedll.getAll();
        for (OrderDetail orde : listorderdetail) {
            cbPay_method.addItem(orde.getPayment_method());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFind = new javax.swing.JButton();
        cbTenKH = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbSanpham = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPay_method = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtmadon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaDetailHD = new javax.swing.JTextField();
        txtfind = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbshow = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnSanPham = new javax.swing.JMenu();
        mnKhachHang = new javax.swing.JMenu();
        mnHoaDon = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        miThayDoiTT = new javax.swing.JMenuItem();
        miThongTinNGuoidung = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Chi Tiết Hóa Đơn");

        btFind.setText("Find");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        jLabel10.setText("VNĐ");

        jLabel2.setText("Mã hóa đơn ");

        cbSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSanphamActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày lập");

        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });
        txtSoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoluongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoluongKeyReleased(evt);
            }
        });

        jLabel4.setText("Tên khách hàng");

        jLabel5.setText("Sản phẩm");

        cbPay_method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPay_methodActionPerformed(evt);
            }
        });

        jLabel6.setText("Số lượng");

        txtmadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmadonActionPerformed(evt);
            }
        });
        txtmadon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmadonKeyPressed(evt);
            }
        });

        jLabel7.setText("Giá");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel8.setText("Phương thức thanh toán");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã đơn");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý chi tiết hóa đơn");

        txtMaDetailHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaDetailHDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaDetailHDKeyReleased(evt);
            }
        });

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbshow);

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenu2.setText("Edit");

        mnSanPham.setText("Quản lý sản phẩm");
        mnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSanPhamMouseClicked(evt);
            }
        });
        jMenu2.add(mnSanPham);

        mnKhachHang.setText("Quản lý khách hàng");
        mnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnKhachHangMouseClicked(evt);
            }
        });
        jMenu2.add(mnKhachHang);

        mnHoaDon.setText("Quản lý hóa đơn");
        mnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnHoaDonMouseClicked(evt);
            }
        });
        jMenu2.add(mnHoaDon);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miThayDoiTT.setText("Thay đổi thông tin đăng nhập");
        miThayDoiTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miThayDoiTTMouseClicked(evt);
            }
        });
        miThayDoiTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miThayDoiTTActionPerformed(evt);
            }
        });
        jMenu1.add(miThayDoiTT);

        miThongTinNGuoidung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        miThongTinNGuoidung.setText("Info");
        miThongTinNGuoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miThongTinNGuoidungMouseClicked(evt);
            }
        });
        miThongTinNGuoidung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miThongTinNGuoidungActionPerformed(evt);
            }
        });
        jMenu1.add(miThongTinNGuoidung);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Thoát");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDetailHD, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtmadon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnxoa)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbPay_method, 0, 240, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsua)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtfind)
                .addGap(18, 18, 18)
                .addComponent(btFind)
                .addGap(27, 27, 27))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFind)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtMaDetailHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPay_method, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miThayDoiTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miThayDoiTTMouseClicked
        // TODO add your handling code here:
        //khi lick
        QuenPass qp = new QuenPass();
        qp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miThayDoiTTMouseClicked

    private void miThayDoiTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miThayDoiTTActionPerformed
        // TODO add your handling code here:
        QuenPass pass = new QuenPass();
        pass.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_miThayDoiTTActionPerformed

    private void miThongTinNGuoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miThongTinNGuoidungMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Nhóm 6");
    }//GEN-LAST:event_miThongTinNGuoidungMouseClicked

    private void miThongTinNGuoidungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miThongTinNGuoidungActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Nhóm 6");
    }//GEN-LAST:event_miThongTinNGuoidungActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSanPhamMouseClicked
        // TODO add your handling code here:
        Main ma = new Main();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnSanPhamMouseClicked

    private void mnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnKhachHangMouseClicked
        // TODO add your handling code here:
        GuiUser us = new GuiUser();
        us.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnKhachHangMouseClicked

    private void mnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnHoaDonMouseClicked
        // TODO add your handling code here:
        QLHOADON ql = new QLHOADON();
        ql.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnHoaDonMouseClicked

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
        String find = txtfind.getText();

        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_btFindActionPerformed

    private void cbSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSanphamActionPerformed

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void txtSoluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoluongKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongKeyPressed

    private void txtSoluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoluongKeyReleased
        // TODO add your handling code here:
        //hàm bat loi nhap 
        listproduct = prodll.getAll();
        int rowPro = cbSanpham.getSelectedIndex();
        int idPro = listproduct.get(rowPro).getquantity();
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtSoluong.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Số lượng là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtSoluong.requestFocus();
            txtSoluong.setText("");
        } else if (Integer.parseInt(txtSoluong.getText()) - idPro > 0) {
            JOptionPane.showMessageDialog(this, "Số lượng trong kho không đủ");
            txtSoluong.setText(String.valueOf(idPro));

        } else {

            //  int row=tbshow.getSelectedRow();
            int idPro1 = listproduct.get(rowPro).getproid();
            String kt = txtSoluong.getText();

            if (!kt.isEmpty()) {
                int giapro = listproduct.get(idPro1).getprice();
                int Soluong = Integer.parseInt((txtSoluong.getText()));

                int gia = Soluong * giapro;
                txtGia.setText(String.valueOf(gia));
                //  String giaf1=txtGia.getText();
            }
        }
    }//GEN-LAST:event_txtSoluongKeyReleased

    private void cbPay_methodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPay_methodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPay_methodActionPerformed

    private void txtmadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmadonActionPerformed

    private void txtmadonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmadonKeyPressed
        // TODO add your handling code here:
        //hàm bat loi nhap 
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtmadon.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Mã là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtmadon.requestFocus();
            txtmadon.setText("");
        }
    }//GEN-LAST:event_txtmadonKeyPressed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        //button them thong tin san pham
        listorderdetail = ordedll.getAll();
        listproduct = prodll.getAll();
        listuser = userdll.getAll();

        int MaDetailHD = Integer.parseInt(txtMaDetailHD.getText());
        String Date = txtDate.getText();
        int rowUser = cbTenKH.getSelectedIndex();
        int idUser = listuser.get(rowUser).getUserid();

        int rowPro = cbSanpham.getSelectedIndex();
        int idPro = listproduct.get(rowPro).getproid();

        int Soluong = Integer.parseInt(txtSoluong.getText());

        int Gia1 = Integer.parseInt(txtGia.getText());

        int rowPay = cbPay_method.getSelectedIndex();
        String idPay = listorderdetail.get(rowPay).getPayment_method();

        int Orderid = Integer.parseInt(txtmadon.getText());

        OrderDetail orde = new OrderDetail();

        orde.setOrderDetailId(MaDetailHD);
        orde.setDate(Date);
        orde.setUserID(idUser);
        orde.setProductID(idPro);
        orde.setQuantity(Soluong);
        orde.setPrice(Gia1);
        orde.setPayment_method(idPay);
        orde.setOrderID(Orderid);
        if (ordedll.AddData(orde)) {
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            Bliding();
            listproduct = prodll.getAll();

            Product pro1 = new Product();
            int rowsp = cbSanpham.getSelectedIndex();
            int idsp = listproduct.get(rowsp).getproid();
            int SPpass = listproduct.get(rowPro).getquantity();
            int sl = Integer.parseInt(txtSoluong.getText());
            sl = SPpass - sl;
            pro1.setquantity(sl);
            pro1.setproId(idsp);
            if (prodll.UpdateSL(pro1)) {
                JOptionPane.showMessageDialog(this, "Đã cập nhập số lượng");
                
            }
            txtDate.setText("");
            txtGia.setText("");
            txtMaDetailHD.setText("");
            txtSoluong.setText("");
            txtmadon.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        //button sua thong tin san pham
        if (tbshow.getSelectedRow() != -1) {
            listorderdetail = ordedll.getAll();
            listproduct = prodll.getAll();
            listuser = userdll.getAll();

            int MaDetailHD = Integer.parseInt(txtMaDetailHD.getText());
            String Date = txtDate.getText();
            int rowUser = cbTenKH.getSelectedIndex();
            int idUser = listuser.get(rowUser).getUserid();

            int rowPro = cbSanpham.getSelectedIndex();
            int idPro = listproduct.get(rowPro).getproid();

            int Soluong = Integer.parseInt(txtSoluong.getText());

            int Gia1 = Integer.parseInt(txtGia.getText());

            int rowPay = cbPay_method.getSelectedIndex();
            String idPay = listorderdetail.get(rowPay).getPayment_method();

            int Orderid = Integer.parseInt(txtmadon.getText());

       
            OrderDetail orde = new OrderDetail();
            int row = tbshow.getSelectedRow();
            orde.setOrderDetailId(listorderdetail.get(row).getOrderDetailId());
            orde.setDate(Date);
            orde.setUserID(idUser);
            orde.setProductID(idPro);
            orde.setQuantity(Soluong);
            orde.setPrice(Gia1);
            orde.setPayment_method(idPay);
            orde.setOrderID(Orderid);
            if (ordedll.UpDateData(orde)) {
                JOptionPane.showMessageDialog(this, "Sua thanh cong");
                Bliding();
                listproduct = prodll.getAll();

            } else {
                JOptionPane.showMessageDialog(this, "Sua that bai");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Mời chọn dòng cần sửa");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        //button xoa thong tin san pham
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            listorderdetail = ordedll.getAll();
            listproduct = prodll.getAll();
            int sl = Integer.parseInt(txtSoluong.getText());
            int getidrowPro = cbSanpham.getSelectedIndex();
            int idPro12 = listproduct.get(getidrowPro).getproid();
            int SL = listproduct.get(getidrowPro).getquantity();

            if (ordedll.DelData(listorderdetail.get(row).getOrderDetailId())) {
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                Bliding();

                int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhập lại số lượng sản phẩm ko?", "Thông báo", JOptionPane.YES_OPTION);
                if (kq == JOptionPane.YES_OPTION) {
                    SL = SL + sl;
                    Product pro1 = new Product();
                    pro1.setquantity(SL);
                    pro1.setproId(idPro12);
                    if (prodll.UpdateSL(pro1)) {
                        JOptionPane.showMessageDialog(this, "Đã cập nhập số lượng");
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Update that bai");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chon dong can xoa");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtMaDetailHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDetailHDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDetailHDKeyPressed

    private void txtMaDetailHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaDetailHDKeyReleased
        // TODO add your handling code here:
        //ham bat loi nhap
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtMaDetailHD.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Mã là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtMaDetailHD.requestFocus();
            txtMaDetailHD.setText("");
        }
        int row = tbshow.getRowCount();
        int ma = row + 1;

        /*  if(Integer.parseInt( txtmasp.getText())<ma)
        {

            JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
            txtmasp.setText(Integer.toString(ma));
        }*/
        for (int i = 0; i < row; i++) {
            if (txtMaDetailHD.getText().equals(String.valueOf(tbshow.getValueAt(i, 0)))) {
                JOptionPane.showMessageDialog(this, "Không được trùng mã");
                // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
                // txtmasp.setText(String.valueOf(ma1+1));
                txtMaDetailHD.setText("");
            }
        }
    }//GEN-LAST:event_txtMaDetailHDKeyReleased

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:
        //tim là in ra thong tin can tim
        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyPressed

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbshowMouseClicked
        // TODO add your handling code here:
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            txtMaDetailHD.setText(String.valueOf(tbshow.getValueAt(row, 0)));
            txtDate.setText(String.valueOf(tbshow.getValueAt(row, 1)));
            cbTenKH.setSelectedItem(tbshow.getValueAt(row, 2));
            cbSanpham.setSelectedItem(tbshow.getValueAt(row, 3));
            txtSoluong.setText(String.valueOf(tbshow.getValueAt(row, 4)));
            txtGia.setText(String.valueOf(tbshow.getValueAt(row, 5)));
            cbPay_method.setSelectedItem(tbshow.getValueAt(row, 6));
            txtmadon.setText(String.valueOf(tbshow.getValueAt(row, 7)));

        }
    }//GEN-LAST:event_tbshowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiOrderDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiOrderDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFind;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbPay_method;
    private javax.swing.JComboBox<String> cbSanpham;
    private javax.swing.JComboBox<String> cbTenKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miThayDoiTT;
    private javax.swing.JMenuItem miThongTinNGuoidung;
    private javax.swing.JMenu mnHoaDon;
    private javax.swing.JMenu mnKhachHang;
    private javax.swing.JMenu mnSanPham;
    private javax.swing.JTable tbshow;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDetailHD;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtmadon;
    // End of variables declaration//GEN-END:variables
}
