/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.CheckKituDLL;
import DLL.UserDLL;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sang Luu Phuoc
 */
public class GuiUser extends javax.swing.JFrame {

    /**
     * Creates new form GuiUser
     */
    // tạo Arraylist để chứa thông của thực thể
    ArrayList<User> listuser = new ArrayList<User>();
    UserDLL userdll = new UserDLL();

    CheckKituDLL checkdll = new CheckKituDLL();

    public GuiUser() {
        initComponents();
        Bliding();
        
        int row = tbshow.getRowCount();
        // vòng sét ID lớn nhất và in sẵn ID cho sản phẩm tiếp theo
        for (int i = 1; i < row; i++) {
            int max = Integer.parseInt(String.valueOf((tbshow.getValueAt(0, 0))));
            if (max < Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)))) {
                max = Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)));

            }
            max = max + 1;
            //in ra txt ID sản pham tiep theo
            txtIDKH.setText(String.valueOf(max));
        }
    }
    // phương thực bảng động và add các giá trị vào bảng
    public void Bliding() {
        listuser = userdll.getAll();
        Vector clums = new Vector();
        clums.add("Mã khach hàng");
        clums.add("Ten khách hàng");
        clums.add("Số điện thoại");
        clums.add("Địa chỉ");
        clums.add("Tuổi");
         // số hàng đưuọc add
        Vector data = new Vector();
        for (User us : listuser) {
            Vector row = new Vector();
            row.add(us.getUserid());
            row.add(us.getFullname());
            row.add(us.getphone());
            row.add(us.getAddress());
            row.add(us.getage());
            data.add(row);

        }
        DefaultTableModel dtm = new DefaultTableModel(data, clums);
        // đưa vào bảng
        tbshow.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtfind = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIDKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbshow = new javax.swing.JTable();
        txtTuoi = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        mnThaydoithongtin = new javax.swing.JMenu();
        Inthongtinnguoilam = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnsanpham = new javax.swing.JMenuItem();
        mnhoadon = new javax.swing.JMenuItem();
        mnhoadonct = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Khách Hàng");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Khách hàng");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên khách hàng");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel4.setText("Số điện thoại");

        txtfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfindMouseClicked(evt);
            }
        });
        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        jLabel5.setText("Địa chỉ");

        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        jLabel6.setText("Tuổi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Khách Hàng");

        txtIDKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKHKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKHKeyReleased(evt);
            }
        });

        txtTenKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKHKeyReleased(evt);
            }
        });

        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        txtDiachi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiachiKeyReleased(evt);
            }
        });

        tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbshow);

        txtTuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTuoiKeyPressed(evt);
            }
        });

        jMenuBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuBar1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        file.setText("File");

        mnThaydoithongtin.setText("Thay đổi thông tin đăng nhập");
        mnThaydoithongtin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnThaydoithongtinMouseClicked(evt);
            }
        });
        mnThaydoithongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThaydoithongtinActionPerformed(evt);
            }
        });
        file.add(mnThaydoithongtin);

        Inthongtinnguoilam.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        Inthongtinnguoilam.setText("Info");
        file.add(Inthongtinnguoilam);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Thoát");
        file.add(jMenuItem2);

        jMenuBar1.add(file);

        jMenu2.setText("Edit");

        mnsanpham.setText("Quản lý sàn phẩm");
        mnsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsanphamActionPerformed(evt);
            }
        });
        jMenu2.add(mnsanpham);

        mnhoadon.setText("Quản lý hóa đơn");
        mnhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhoadonActionPerformed(evt);
            }
        });
        jMenu2.add(mnhoadon);

        mnhoadonct.setText("Quản lý hóa đơn chi tiết");
        mnhoadonct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhoadonctActionPerformed(evt);
            }
        });
        jMenu2.add(mnhoadonct);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnxoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtIDKH)
                            .addComponent(txtSDT))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(find)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(find)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtIDKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnThaydoithongtinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnThaydoithongtinMouseClicked
        // TODO add your handling code here:
        QuenPass qp = new QuenPass();
        qp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnThaydoithongtinMouseClicked

    private void mnsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsanphamActionPerformed
        // TODO add your handling code here:
        Main ma = new Main();
        ma.setVisible(true);
        this.setVisible(false);
        //chuyên sang thong tin sản pham
    }//GEN-LAST:event_mnsanphamActionPerformed

    private void mnhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhoadonActionPerformed
        // TODO add your handling code here:
        QLHOADON qlh = new QLHOADON();
        qlh.setVisible(true);
        this.setVisible(false);
       //chuyên sang thong tin hoa don
    }//GEN-LAST:event_mnhoadonActionPerformed

    private void mnhoadonctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhoadonctActionPerformed
        // TODO add your handling code here:
        GuiOrderDetail god = new GuiOrderDetail();
        god.setVisible(true);
        this.setVisible(false);
         //chuyên sang thong tin hoa don chi tiet
    }//GEN-LAST:event_mnhoadonctActionPerformed

    private void jMenuBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1AncestorAdded

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        //button them thong tin vao bản
        listuser = userdll.getAll();
        int userid = Integer.parseInt(txtIDKH.getText());
        String tenkh = txtTenKH.getText();
        String phone = txtSDT.getText();
        String Diachi = txtDiachi.getText();
        int Age = Integer.parseInt(txtTuoi.getText());

        User us = new User();
        us.setUserid(userid);
        us.setFulname(tenkh);
        us.setphone(phone);
        us.setaddress(Diachi);
        us.setage(Age);
        if (userdll.AddData(us)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            Bliding();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        //button sua thong tin 
        listuser = userdll.getAll();
        int userid = Integer.parseInt(txtIDKH.getText());
        String tenkh = txtTenKH.getText();
        String phone = txtSDT.getText();
        String Diachi = txtDiachi.getText();
        int Age = Integer.parseInt(txtTuoi.getText());
        int row = tbshow.getSelectedRow();

        User us = new User();
        us.setUserid(listuser.get(row).getUserid());
        us.setFulname(tenkh);
        us.setphone(phone);
        us.setaddress(Diachi);
        us.setage(Age);
        if (userdll.UpdateData(us)) {
            JOptionPane.showMessageDialog(this, "Update thành công");
            Bliding();
        } else {
            JOptionPane.showMessageDialog(this, "Update thât bại");
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        //button xoa thong tin khoi sql
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            listuser = userdll.getAll();

            if (userdll.DelData(listuser.get(row).getUserid())) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                Bliding();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtfindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfindMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfindMouseClicked

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtfindKeyPressed

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        //tim và in ra thong tin can tim
        String find = txtfind.getText();

        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_findActionPerformed

    private void txtIDKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKHKeyPressed
        // TODO add your handling code here:x

    }//GEN-LAST:event_txtIDKHKeyPressed

    private void txtIDKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKHKeyReleased
        // TODO add your handling code here:
        //hàm bat loi nhap  
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtIDKH.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Mã là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtIDKH.requestFocus();
            txtIDKH.setText("");
        }

        int row = tbshow.getRowCount();
        int ma = row + 1;

       
        for (int i = 0; i < row; i++) {
            if (txtIDKH.getText().equals(String.valueOf(tbshow.getValueAt(i, 0)))) {
                JOptionPane.showMessageDialog(this, "Không được trùng mã");
             
                txtIDKH.setText("");
            }
        }

    }//GEN-LAST:event_txtIDKHKeyReleased

    private void txtTenKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKHKeyReleased
        // TODO add your handling code here:
        if (checkdll.checksyb(txtTenKH.getText())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtTenKH.setText("");
        }
    }//GEN-LAST:event_txtTenKHKeyReleased

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        // TODO add your handling code here:
        //hàm bat loi nhap 
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtSDT.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Số điện thọai là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtSDT.requestFocus();
            txtIDKH.setText("");
        }
    }//GEN-LAST:event_txtSDTKeyPressed

    private void txtDiachiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiachiKeyReleased
        // TODO add your handling code here:
        if (checkdll.checksyb(txtDiachi.getText())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtDiachi.setText("");
        }
    }//GEN-LAST:event_txtDiachiKeyReleased

    private void tbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbshowMouseClicked
        // TODO add your handling code here:
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            txtIDKH.setText(String.valueOf(tbshow.getValueAt(row, 0)));
            txtTenKH.setText(String.valueOf(tbshow.getValueAt(row, 1)));
            txtSDT.setText(String.valueOf(tbshow.getValueAt(row, 2)));
            txtDiachi.setText(String.valueOf(tbshow.getValueAt(row, 3)));
            txtTuoi.setText(String.valueOf(tbshow.getValueAt(row, 4)));

        }
    }//GEN-LAST:event_tbshowMouseClicked

    private void txtTuoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuoiKeyPressed
        // TODO add your handling code here:í
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtTuoi.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Tuổi là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtTuoi.requestFocus();
            txtTuoi.setText("");
        }
    }//GEN-LAST:event_txtTuoiKeyPressed

    private void mnThaydoithongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThaydoithongtinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnThaydoithongtinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Inthongtinnguoilam;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JMenu file;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnThaydoithongtin;
    private javax.swing.JMenuItem mnhoadon;
    private javax.swing.JMenuItem mnhoadonct;
    private javax.swing.JMenuItem mnsanpham;
    private javax.swing.JTable tbshow;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtIDKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTuoi;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
