/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.AccountDLL;
import DLL.CategoryDLL;
import DLL.CheckKituDLL;
import DLL.ProductDLL;
import DLL.UserDLL;
import Entity.Category;
import Entity.Product;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sang Luu Phuoc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    // tạo Arraylist để chứa thông của thực thể
    ProductDLL prodll = new ProductDLL();
    ArrayList<Product> listpro = new ArrayList<>();

    CategoryDLL catedll = new CategoryDLL();
    ArrayList<Category> listcate = new ArrayList<>();

    UserDLL userDLL = new UserDLL();
    ArrayList<User> listuser = new ArrayList<>();

    AccountDLL accdll = new AccountDLL();

    CheckKituDLL checkdll = new CheckKituDLL();

    public Main() {
        initComponents();
        Bliding();
        BlidingSize();
        BlidingCat();
        // lấy số hàng từ số lương khi chạy phương thức Bliding
        int row = tbproduct.getRowCount();
        // vòng sét ID lớn nhất và in sẵn ID cho sản phẩm tiếp theo
        for (int i = 1; i < row; i++) {
            int max = Integer.parseInt(String.valueOf((tbproduct.getValueAt(0, 0))));
            if (max < Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)))) {
                max = Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));

                // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
                // txtmasp.setText(String.valueOf(ma1+1));
                //txtmasp.setText("");
            }
            max = max + 1;
            // in ra txt 
            txtmasp.setText(String.valueOf(max));
        }
    }
     // phương thực bảng động và add các giá trị vào bảng
    public void Bliding() {
        listpro = prodll.getAll();
        Vector culms = new Vector();
        culms.add("Mã sản phâm");
        culms.add("Tên sản phẩm");
        culms.add("Nhãn hiệu");
        culms.add("Giá");
        culms.add("Số lượng");
        culms.add("Kích cỡ");
        culms.add("Category");
        // số hàng đưuọc add
        Vector data = new Vector();
         // vọng lặp in gia trị
        for (Product pro : listpro) {
            Vector row = new Vector();
            row.add(pro.getproid());
            row.add(pro.getname());
            row.add(pro.getbrand());
            row.add(pro.getprice());
            row.add(pro.getquantity());

            listpro = prodll.getbyID(pro.getproid());
            try {
                if (listpro.size() > 0) {
                    row.add(listpro.get(0).getDesc());
                } else {
                    row.add("Không có");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            listcate = catedll.getByID(pro.getcatid());
            try {
                if (listcate.size() > 0) {
                    row.add(listcate.get(0).getname());
                } else {
                    row.add("Không có");
                }
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Ko có dư liệu!!!!!");
            }

            data.add(row);

            //  row.add(pro.getDesc());
            // row.add(pro.getcatid());
        }
        DefaultTableModel dtm = new DefaultTableModel(data, culms);
        tbproduct.setModel(dtm);
    }
   // phương thức lấy hết thông tin thể loại và add item đê chọn
    public void BlidingCat() {
        listcate = catedll.getAll();
        for (Category ca : listcate) {
            cbCate.addItem(ca.getname());
        }

    }
    // phương thức add item để chọn
    public void BlidingSize() {
        listpro = prodll.getAll();

        cbSize.addItem("35");
        cbSize.addItem("36");
        cbSize.addItem("37");
        cbSize.addItem("38");
        cbSize.addItem("39");
        cbSize.addItem("40");
        cbSize.addItem("41");
        cbSize.addItem("42");
        cbSize.addItem("43");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnxoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        txtfind = new javax.swing.JTextField();
        txtbrand = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbproduct = new javax.swing.JTable();
        txtgia = new javax.swing.JTextField();
        cbSize = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbCate = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        mnthaydoitt = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnkhachhang = new javax.swing.JMenu();
        mnhoadon = new javax.swing.JMenu();
        mnhoadonct = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Shop Giày");

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel7.setText("Category");

        jLabel8.setText("Mã Sản phẩm");

        jLabel6.setText("Size");

        txtmasp.setEditable(false);
        txtmasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaspActionPerformed(evt);
            }
        });
        txtmasp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaspKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmaspKeyReleased(evt);
            }
        });

        txttensp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttenspKeyPressed(evt);
            }
        });

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        txtbrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbrandKeyReleased(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Quản Lý Shop Giày");

        txtsoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsoluongActionPerformed(evt);
            }
        });
        txtsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsoluongKeyPressed(evt);
            }
        });

        tbproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbproduct);

        txtgia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgiaKeyPressed(evt);
            }
        });

        jLabel2.setText("Tên sản phẩm");

        cbCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCateActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhãn hiệu");

        btnthem.setText("Thêm sản phẩm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá ");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel5.setText("Số lượng");

        jMenu6.setText("File");

        mnthaydoitt.setText("Thay đổi thông tin đăng nhâp");
        mnthaydoitt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnthaydoittMouseClicked(evt);
            }
        });
        jMenu6.add(mnthaydoitt);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Thoát");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Info");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Quản Lý");

        mnkhachhang.setText("Quản lý khách hàng");
        mnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnkhachhangMouseClicked(evt);
            }
        });
        jMenu7.add(mnkhachhang);

        mnhoadon.setText("Quản lý hóa đơn");
        mnhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnhoadonMouseClicked(evt);
            }
        });
        jMenu7.add(mnhoadon);

        mnhoadonct.setText("Quản lý chi tiết hóa đơn");
        mnhoadonct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnhoadonctMouseClicked(evt);
            }
        });
        jMenu7.add(mnhoadonct);

        jMenuBar2.add(jMenu7);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttensp, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtbrand)
                            .addComponent(txtmasp))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind))
                        .addGap(2, 2, 2)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnthaydoittMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnthaydoittMouseClicked
        // TODO add your handling code here:
        QuenPass qp = new QuenPass();
        qp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnthaydoittMouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Phần mềm được làm bởi Nhóm 6");
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Phần mềm được làm bởi Nhóm 6");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnkhachhangMouseClicked
        // TODO add your handling code here:

        GuiUser us = new GuiUser();
        us.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_mnkhachhangMouseClicked

    private void mnhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnhoadonMouseClicked
        // TODO add your handling code here:
        //hiên thị bản thong tin hoa don
        QLHOADON qlhd = new QLHOADON();
        qlhd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnhoadonMouseClicked

    private void mnhoadonctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnhoadonctMouseClicked
        // TODO add your handling code here:
        //hiện thi bản thông tin hóa hơn chi tiết
        GuiOrderDetail orde = new GuiOrderDetail();
        orde.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnhoadonctMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        //xoa thong tin sảm phảm  vào sql
        if (tbproduct.getSelectedRow() != -1) {
            int row = tbproduct.getSelectedRow();
            listpro = prodll.getAll();

            if (prodll.DelData(listpro.get(row).getproid())) {
                Bliding();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtmaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaspActionPerformed

    private void txtmaspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaspKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaspKeyPressed

    private void txtmaspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaspKeyReleased
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtmasp.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Giá là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtmasp.requestFocus();
            txtmasp.setText("");
        }
        int row = tbproduct.getRowCount();
        int ma = row + 1;

        /*  if(Integer.parseInt( txtmasp.getText())<ma)
        {

            JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
            txtmasp.setText(Integer.toString(ma));
        }*/
        for (int i = 0; i < row; i++) {
            if (txtmasp.getText().equals(String.valueOf(tbproduct.getValueAt(i, 0)))) {
                JOptionPane.showMessageDialog(this, "Không được trùng mã");
                // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
                // txtmasp.setText(String.valueOf(ma1+1));
                txtmasp.setText("");
            }
        }
    }//GEN-LAST:event_txtmaspKeyReleased

    private void txttenspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttenspKeyPressed
        // TODO add your handling code here:

        if (checkdll.checksyb(txttensp.getText())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txttensp.setText("");
        }
    }//GEN-LAST:event_txttenspKeyPressed

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtfindKeyPressed

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbproduct.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbproduct.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void txtbrandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbrandKeyReleased
        // TODO add your handling code here:
        //bat kí tu dat biet
        if (checkdll.checksyb(txtbrand.getText())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtbrand.setText("");
        }
    }//GEN-LAST:event_txtbrandKeyReleased

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        //tim thong tin và in ra thong tin cần tim
        String find = txtfind.getText();

        DefaultTableModel dtm = (DefaultTableModel) tbproduct.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbproduct.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(find));

    }//GEN-LAST:event_btnFindActionPerformed

    private void txtsoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongActionPerformed

    private void txtsoluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoluongKeyPressed
        // TODO add your handling code here:
        //bat loi nhap thong tin
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtsoluong.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Số lượng là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtsoluong.requestFocus();
            txtsoluong.setText("");
        }
    }//GEN-LAST:event_txtsoluongKeyPressed

    private void tbproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductMouseClicked
        // TODO add your handling code here:
        //lick chon thong tin muốn sua, xoa
        if (tbproduct.getSelectedRow() != -1) {
            int row = tbproduct.getSelectedRow();
            listpro = prodll.getAll();
            txtmasp.setText(String.valueOf(tbproduct.getValueAt(row, 0)));
            txttensp.setText(String.valueOf(tbproduct.getValueAt(row, 1)));
            txtbrand.setText(String.valueOf(tbproduct.getValueAt(row, 2)));
            txtgia.setText(String.valueOf(tbproduct.getValueAt(row, 3)));
            txtsoluong.setText(String.valueOf(tbproduct.getValueAt(row, 4)));
            //cbSize.addItem(String.valueOf(tbproduct.getValueAt(row, 5)));
            //cbCate.addItem(String.valueOf(tbproduct.getValueAt(row, 6)));
            cbSize.setSelectedItem(tbproduct.getValueAt(row, 5));
            cbCate.setSelectedItem(tbproduct.getValueAt(row, 6));
        }
    }//GEN-LAST:event_tbproductMouseClicked

    private void txtgiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgiaKeyPressed
        // TODO add your handling code here:ơngj
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtgia.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Giá là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtgia.requestFocus();
            txtgia.setText("");
        }
    }//GEN-LAST:event_txtgiaKeyPressed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        //them thong tin sảm phảm mới vào sql
        listcate = catedll.getAll();
        listpro = prodll.getAll();
        int gia = 0;
        int soluong = 0;
        int Proid = 0;
        int Cate = cbCate.getSelectedIndex();
        String Tensp = txttensp.getText();
        String brand = txtbrand.getText();
        String Des = String.valueOf(cbSize.getSelectedItem());
        int Cateid = listcate.get(Cate).getcatid();
        if (Tensp.isEmpty() || brand.isEmpty() || Des.isEmpty() || txtgia.getText().isEmpty() || txtsoluong.getText().isEmpty()
                || txtmasp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong Thong tin sp !!");
        } else {
            Product pr = new Product();
            Proid = Integer.parseInt(txtmasp.getText());
            soluong = Integer.parseInt(txtsoluong.getText());
            gia = Integer.parseInt(txtgia.getText());
            pr.setproId(Proid);
            pr.setquantity(soluong);
            pr.setprice(gia);
            pr.setname(Tensp);
            pr.setbrand(brand);
            pr.setDesc(Des);
            pr.setcatid(Cateid);
            if (prodll.Adddata(pr)) {
                Bliding();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                txtbrand.setText("");
                txtfind.setText("");
                txtmasp.setText(String.valueOf(Proid + 1));
                txtgia.setText("");
                txtsoluong.setText("");
                txttensp.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        //sua thong tin sảm phảm trong sql
        listcate = catedll.getAll();
        listpro = prodll.getAll();
        int Proid = Integer.parseInt(txtmasp.getText());
        String Tensp = txttensp.getText();
        String brand = txtbrand.getText();
        int gia = Integer.parseInt(txtgia.getText());
        int soluong = Integer.parseInt(txtsoluong.getText());
        // int Des=cbSize.getSelectedIndex();
        String Des = String.valueOf(cbSize.getSelectedItem());
        int Cate = cbCate.getSelectedIndex();
        int row = tbproduct.getSelectedRow();
        //   int Desid=listpro.get(Des).getproid();
        int Cateid = listcate.get(Cate).getcatid();

        Product pr = new Product();
        pr.setproId(listpro.get(row).getproid());
        pr.setname(Tensp);
        pr.setbrand(brand);
        pr.setprice(gia);
        pr.setquantity(soluong);
        pr.setDesc(Des);
        pr.setcatid(Cateid);
        if (prodll.UpdateData(pr)) {
            Bliding();
            JOptionPane.showMessageDialog(this, "Update thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại");
        }

    }//GEN-LAST:event_btnsuaActionPerformed

    private void cbCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbCate;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnhoadon;
    private javax.swing.JMenu mnhoadonct;
    private javax.swing.JMenu mnkhachhang;
    private javax.swing.JMenu mnthaydoitt;
    private javax.swing.JTable tbproduct;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttensp;
    // End of variables declaration//GEN-END:variables
}
