/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DLL.CheckKituDLL;
import DLL.OrderDLL;
import DLL.OrderDetailDLL;
import DLL.ProductDLL;
import DLL.UserDLL;
import Entity.Order;
import Entity.OrderDetail;
import Entity.Product;
import Entity.User;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sang Luu Phuoc
 */
public class QLHOADON extends javax.swing.JFrame {

    /**
     * Creates new form QLHOADON
     */
    // tạo Arraylist để chứa thông của thực thể
    OrderDLL orderdll = new OrderDLL();
    ArrayList<Order> listorder = new ArrayList<>();

    ProductDLL prodll = new ProductDLL();
    ArrayList<Product> listproduct = new ArrayList<>();

    UserDLL userdll = new UserDLL();
    ArrayList<User> listuser = new ArrayList<>();

    OrderDetailDLL oreddll = new OrderDetailDLL();
    ArrayList<OrderDetail> listorde = new ArrayList<>();

    CheckKituDLL checkdll = new CheckKituDLL();

    public QLHOADON() {
        initComponents();
        Bliding();
        BlidingUser();
        // lấy số hàng từ số lương khi chạy phương thức Bliding
        int row = tbshow.getRowCount();
        // vòng sét ID lớn nhất và in sẵn ID cho sản phẩm tiếp theo
        for (int i = 1; i < row; i++) {
            int max = Integer.parseInt(String.valueOf((tbshow.getValueAt(0, 0))));
            if (max < Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)))) {
                max = Integer.parseInt(String.valueOf(tbshow.getValueAt(i, 0)));
             
            }            
            max = max + 1;
            //in sẵn ID cho sản phẩm tiếp theo
            txtMaHD.setText(String.valueOf(max));
        }
    }
    // phương thực bảng động và add các giá trị vào bảng
    public void Bliding() {
        listorder = orderdll.getAll();
        Vector colums = new Vector();
        colums.add("Mã Hóa Đơn");

        colums.add("Tên hóa đơn");

        colums.add("Tên khách hàng");

        colums.add("Giá");
        colums.add("Ngày tạo");
        Vector data = new Vector();
        for (Order or : listorder) {
            Vector row = new Vector();
            row.add(or.getOrderID());
            row.add(or.getName());
            listuser = userdll.getbyID(or.getUserID());
            if (listuser.size() > 0) {
                row.add(listuser.get(0).getFullname());
            } else {
                row.add("Chua co du lieu");
            }

            row.add(or.getPrice());
            row.add(or.getDate());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, colums);
        tbshow.setModel(dtm);

    }
    // phương thức lấy hết thông tin và add item để chọn
    public void BlidingUser() {
        listuser = userdll.getAll();
        for (User us : listuser) {
            cbTenKH.addItem(us.getFullname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDate = new javax.swing.JTextField();
        txtGiatien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfind = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        find = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbTenKH = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbshow = new javax.swing.JTable();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        txtMaHD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenHD = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnsanpham = new javax.swing.JMenu();
        mnkhachhang = new javax.swing.JMenu();
        mnhoadonct = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Hóa Đơn");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtGiatien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiatienActionPerformed(evt);
            }
        });
        txtGiatien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGiatienKeyPressed(evt);
            }
        });

        jLabel4.setText("VNĐ");

        jLabel2.setText("Mã Hóa Đơn");

        jButton4.setText("Xuất Báo cáo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Hóa Đơn");

        txtfind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfindKeyReleased(evt);
            }
        });

        jLabel6.setText("Giá tiên");

        find.setText("Find");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        jLabel8.setText("Khách hàng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản lý hóa đơn");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        tbshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbshow);

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        txtMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHDActionPerformed(evt);
            }
        });
        txtMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaHDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaHDKeyReleased(evt);
            }
        });

        jLabel9.setText("Ngày lập");

        txtTenHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHDActionPerformed(evt);
            }
        });
        txtTenHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenHDKeyReleased(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mnsanpham.setText("Quản lý sản phẩm");
        mnsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnsanphamMouseClicked(evt);
            }
        });
        jMenu2.add(mnsanpham);

        mnkhachhang.setText("Quản lý khách hàng");
        mnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnkhachhangMouseClicked(evt);
            }
        });
        jMenu2.add(mnkhachhang);

        mnhoadonct.setText("Hóa đơn chi tiết");
        mnhoadonct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnhoadonctActionPerformed(evt);
            }
        });
        jMenu2.add(mnhoadonct);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(find)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenHD, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtMaHD))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel8)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton4)
                                            .addComponent(jLabel4)))))
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(find)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnsanphamMouseClicked
        // TODO add your handling code here:
        //hiên thị bản san pham
        Main m = new Main();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnsanphamMouseClicked

    private void mnkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnkhachhangMouseClicked
        // TODO add your handling code here:
        GuiUser user = new GuiUser();
        user.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnkhachhangMouseClicked

    private void mnhoadonctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnhoadonctActionPerformed
        // TODO add your handling code here:
        //hiển thị bản hóa đơn
        GuiOrderDetail guiod = new GuiOrderDetail();
        guiod.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnhoadonctActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtGiatienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiatienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiatienActionPerformed

    private void txtGiatienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiatienKeyPressed
        // TODO add your handling code here:
        //bắt loi nhap so
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtGiatien.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Giá là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtGiatien.requestFocus();
            txtGiatien.setText("");
        }
    }//GEN-LAST:event_txtGiatienKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtfindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtfindKeyPressed

    private void txtfindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfindKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtfind.getText()));
    }//GEN-LAST:event_txtfindKeyReleased

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        //lấy thong và tim thong tin đó trong bản
        String find = txtfind.getText();

        DefaultTableModel dtm = (DefaultTableModel) tbshow.getModel();
        dtm.fireTableDataChanged();
        TableRowSorter trs = new TableRowSorter(dtm);
        tbshow.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(find));
    }//GEN-LAST:event_findActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        //them thong tin hóa hơn vao sql
        listorder = orderdll.getAll();
        listuser = userdll.getAll();
        int Mahd = Integer.parseInt(txtMaHD.getText());
        String Tenhd = txtTenHD.getText();
        String date = txtDate.getText();
        int gia = Integer.parseInt(txtGiatien.getText());
        int rowUser = cbTenKH.getSelectedIndex();

        int idUser = listuser.get(rowUser).getUserid();

        Order or = new Order();

        or.setOrderID(Mahd);
        or.setName(Tenhd);
        or.setUserID(idUser);
        or.setPrice(gia);
        or.setDate(date);
        if (orderdll.AddData(or)) {
            Bliding();
            JOptionPane.showMessageDialog(this, "Them thanh cong");
            txtDate.setText("");
            txtGiatien.setText("");
            txtMaHD.setText("");
            txtTenHD.setText("");
           
            
        } else {
            JOptionPane.showMessageDialog(this, "Them that bai");
        }

    }//GEN-LAST:event_btnthemActionPerformed

    private void tbshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbshowMouseClicked
        // TODO add your handling code here:
  
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            txtMaHD.setText(String.valueOf(tbshow.getValueAt(row, 0)));
            txtTenHD.setText(String.valueOf(tbshow.getValueAt(row, 1)));
            txtGiatien.setText(String.valueOf(tbshow.getValueAt(row, 3)));
            txtDate.setText(String.valueOf(tbshow.getValueAt(row, 4)));
            cbTenKH.setSelectedItem(tbshow.getValueAt(row, 2));
           
        }
    }//GEN-LAST:event_tbshowMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        //sua thong tin hoa don trong sql
        listuser = userdll.getAll();
        listorder = orderdll.getAll();
        int Mahd = Integer.parseInt(txtMaHD.getText());
        String Tenhd = txtTenHD.getText();
        String date = txtDate.getText();
        int gia = Integer.parseInt(txtGiatien.getText());
        int row = tbshow.getSelectedRow();
        int rowUser = cbTenKH.getSelectedIndex();

        int idUser = listuser.get(rowUser).getUserid();

        Order or = new Order();

        or.setOrderID(listorder.get(row).getOrderID());
        or.setName(Tenhd);
        or.setUserID(idUser);
        or.setPrice(gia);
        or.setDate(date);
        if (orderdll.UpdateData(or)) {
            JOptionPane.showMessageDialog(this, "Update thanh cong");
            Bliding();
        } else {
            JOptionPane.showMessageDialog(this, "Update that bai");
        }

    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        //xoa thong tin hóa đơn
        if (tbshow.getSelectedRow() != -1) {
            int row = tbshow.getSelectedRow();
            listorder = orderdll.getAll();

            if (orderdll.DelData(listorder.get(row).getOrderID())) {
                JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                Bliding();
            } else {
                JOptionPane.showMessageDialog(this, "Xoa that bai");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Moi chon dong can xoa");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void txtMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDActionPerformed

    private void txtMaHDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaHDKeyPressed

    private void txtMaHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaHDKeyReleased
        // TODO add your handling code here:
        //bắt lỗi nhâp số
        Pattern pattern = Pattern.compile("\\d*");
        Matcher matcher = pattern.matcher(txtMaHD.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Mã là số", "Warning", JOptionPane.WARNING_MESSAGE);
            txtMaHD.requestFocus();
            txtMaHD.setText("");
        }
        int row = tbshow.getRowCount();
        int ma = row + 1;

        /*  if(Integer.parseInt( txtmasp.getText())<ma)
        {

            JOptionPane.showMessageDialog(this, "Mã tăng và không được trùng mã có sẵn!");
            txtmasp.setText(Integer.toString(ma));
        }*/
        for (int i = 0; i < row; i++) {
            if (txtMaHD.getText().equals(String.valueOf(tbshow.getValueAt(i, 0)))) {
                JOptionPane.showMessageDialog(this, "Không được trùng mã");
                // int ma1=Integer.parseInt(String.valueOf(tbproduct.getValueAt(i, 0)));
                // txtmasp.setText(String.valueOf(ma1+1));
                txtMaHD.setText("");
            }
        }
    }//GEN-LAST:event_txtMaHDKeyReleased

    private void txtTenHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHDActionPerformed

    private void txtTenHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenHDKeyReleased
        // TODO add your handling code here:
        if (checkdll.checksyb(txtTenHD.getText())) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt");
            txtTenHD.setText("");
        }
    }//GEN-LAST:event_txtTenHDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHOADON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHOADON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbTenKH;
    private javax.swing.JButton find;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnhoadonct;
    private javax.swing.JMenu mnkhachhang;
    private javax.swing.JMenu mnsanpham;
    private javax.swing.JTable tbshow;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtGiatien;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTenHD;
    private javax.swing.JTextField txtfind;
    // End of variables declaration//GEN-END:variables
}
